load("//:zephyr_rules.bzl", "zephyr_library")
load("//boards:all.bzl", "BOARD_NAME_SELECT")

_PICOLIBC_SRCS    = glob(["picolibc/*.c"])
_LIBC_COMMON_SRCS = [
    "common/source/errno/errno.c",
    "common/source/stdlib/abort.c",
    "common/source/stdlib/malloc.c",
    "common/source/time/time.c",
]

zephyr_library(
    name = "picolibc",
    board = BOARD_NAME_SELECT,
    srcs = _PICOLIBC_SRCS,
    visibility = ["PUBLIC"],
)

zephyr_library(
    name = "libc_common",
    board = BOARD_NAME_SELECT,
    srcs = _LIBC_COMMON_SRCS,
    visibility = ["PUBLIC"],
)

zephyr_library(
    name = "libc_validate",
    board = BOARD_NAME_SELECT,
    srcs = ["validate_libc.c"],
    supervisor = True,
    visibility = ["PUBLIC"],
)
