load("//:zephyr_rules.bzl", "zephyr_library", "CV_X86", "CV_ARM")

_BOARD = select({CV_X86: "qemu_x86", CV_ARM: "qemu_cortex_m3"})

zephyr_library(
    name = "timer",
    board = _BOARD,
    srcs = select({CV_X86: ["hpet.c", "sys_clock_init.c"], CV_ARM: ["cortex_m_systick.c", "sys_clock_init.c"]}),
    supervisor = True,
    visibility = ["PUBLIC"],
)
