load("//:zephyr_rules.bzl", "zephyr_library", "CV_X86", "CV_ARM")

_BOARD = select({CV_X86: "qemu_x86", CV_ARM: "qemu_cortex_m3"})

zephyr_library(
    name = "posix",
    board = _BOARD,
    srcs = [
        "c_lib_ext/fnmatch.c",
        "c_lib_ext/getentropy.c",
        "c_lib_ext/getopt_shim.c",
    ],
    visibility = ["PUBLIC"],
)
