load("//:zephyr_rules.bzl", "zephyr_library")
load("//boards:all.bzl", "BOARD_NAME_SELECT")

zephyr_library(
    name = "posix",
    board = BOARD_NAME_SELECT,
    srcs = [
        "c_lib_ext/fnmatch.c",
        "c_lib_ext/getentropy.c",
        "c_lib_ext/getopt_shim.c",
    ],
    visibility = ["PUBLIC"],
)
