load("//:zephyr_rules.bzl", "zephyr_library", "CV_X86", "CV_ARM")

_BOARD = select({CV_X86: "qemu_x86", CV_ARM: "qemu_cortex_m3"})

zephyr_library(
    name = "console",
    board = _BOARD,
    srcs = ["uart_console.c"],
    supervisor = True,
    visibility = ["PUBLIC"],
)
