load("//:zephyr_rules.bzl", "zephyr_library")
load("//boards:all.bzl", "BOARD_NAME_SELECT", "driver_src_select")

zephyr_library(
    name = "serial",
    board = BOARD_NAME_SELECT,
    srcs = driver_src_select("serial"),
    supervisor = True,
    visibility = ["PUBLIC"],
)
